### ISSUE TITLE
Game occasionally freezes on servers

### ISSUE THREAD

**Issue by jonot-cyber** [Fabulously-Optimized/fabulously-optimized#457]
### Describe the bug

Soon after joining a hypixel lobby, sometimes, for around ~40 seconds, the game will freeze. Memory usage isn't lower afterwards so I don't think it's the garbage collector

### Modpack version

4.2.0

### Launcher

MultiMC (auto-update)

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

### Additional context

Hardware:
- AMD Ryzen 3 3200G
- RX 6600
- 16gb ram (4gb allocated to Minecraft)
- Running on linux

**Comment by GeefireMC** [comment]
I found a freeze on the server `dev.nucleoid.xyz`, on a fresh FO 4.3.0 instance. The same issue occurs on my lightly modded FO 4.2.1 instance. Attached is my `options.txt` (Although I can't imagine that that would change much) and my `latest.log`.  I've experienced similar freezes on a different server, `play.pvplegacy.net`, but I don't have logs for that, and I doubt they would help anyways considering what these logs look like.

Steps to reproduce:

1. connect to `dev.nucleoid.xyz`
2. type `/game open loopdeloop:quick` (or interact with the NPC and select the (Quick) option)
3. wait for the game to countdown to start
4. The game will freeze for a few seconds when it says "Go!" on screen.

[options.txt](https://github.com/Fabulously-Optimized/fabulously-optimized/files/9540995/options.txt)

[latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/9540998/latest.log)

**Comment by Madis0** [comment]
> Steps to reproduce:
> 
> 1. connect to `dev.nucleoid.xyz`
> 2. type `/game open loopdeloop:quick` (or interact with the NPC and select the (Quick) option)
> 3. wait for the game to countdown to start
> 4. The game will freeze for a few seconds when it says "Go!" on screen.

Hmm. Tried that on 4.3.1 and did not get a freeze.

**Comment by Madis0** [comment]
Should be fixed in 4.3.3.

**Comment by Lalit64** [comment]
@Madis0 It is still freezing installed the latest version (4.4.0) through CurseForge

**Comment by Madis0** [comment]
> @Madis0 It is still freezing installed the latest version (4.4.0) through CurseForge

Did you do a clean install or upgrade from some version?

**Comment by Lalit64** [comment]
@Madis0  I did a clean install

**Comment by Madis0** [comment]
@Lalit64 

Okay. I've asked others and they could not confirm, so it seems to be a separate issue.  Please [ensure you've followed the install instructions](https://fabulously-optimized.gitbook.io/modpack/readme/install-instructions) and if you can continue to reproduce it, make a new issue or support thread in discord with your full system details.
